FROM nginx:latest

RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]