services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    networks:
      - test-repo-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - test-repo-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  test-repo-network:
    driver: bridge
