FROM nginx:latest

RUN apt-get update && apt-get install -y \
    docker.io \
    curl && \
    curl -LO https://dl.k8s.io/release/v1.30.5/bin/linux/amd64/kubectl && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl && \
    apt-get remove --purge -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]