apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: test-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: LoadBalancer